apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: employee-app
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80          # service port
      targetPort: 8080  # container port in backend pod
  type: ClusterIP      # internal cluster access, perfect for backend
