apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: employee-app
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080  # specify NodePort (optional, or let k8s assign one)
  type: NodePort      # change from LoadBalancer to NodePort
