apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: employee-app
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80          # external service port
      targetPort: 3000  # container port in frontend pod
  type: LoadBalancer  # exposes frontend outside cluster (e.g., for testing)
