apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: employee-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: employee_db
            - name: POSTGRES_USER
              value: employee_user
            - name: POSTGRES_PASSWORD
              value: password123
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          emptyDir: {}  
