name: Deploy to K3s Cluster

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG_B64 }}" | base64 --decode > $HOME/.kube/config
        chmod 600 $HOME/.kube/config

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push backend image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-app:latest ./backend
        docker push ${{ secrets.DOCKER_USERNAME }}/backend-app:latest

    - name: Build and push frontend image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend-app:latest ./frontend
        docker push ${{ secrets.DOCKER_USERNAME }}/frontend-app:latest

    - name: Deploy to Kubernetes
      run: kubectl apply -f ./k8s

    - name: Check cluster pods
      run: kubectl get pods --all-namespaces
