name: Deploy to K3s

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG_B64 }}" | base64 --decode > $HOME/.kube/config
        chmod 600 $HOME/.kube/config

    - name: Verify kubectl config
      run: kubectl cluster-info

    - name: Deploy backend
      run: kubectl apply -f k8s/backend-deployment.yaml

    - name: Deploy frontend
      run: kubectl apply -f k8s/frontend-deployment.yaml

    - name: Deploy services
      run: kubectl apply -f k8s/services.yaml
