name: Deploy to Kubernetes

on:
  push:
    paths:
      - k8s/**   # Only trigger when files in k8s folder change

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3   # or any setup kubectl action

      - name: Deploy to cluster
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG_B64 }}
        run: |
          kubectl apply -f k8s/frontend-service.yaml
          
