name: Deploy to K3s Cluster
#testing
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG_B64 }}" | base64 --decode > $HOME/.kube/config
        chmod 600 $HOME/.kube/config

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push backend image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-app:latest ./backend
        docker push ${{ secrets.DOCKER_USERNAME }}/backend-app:latest

    - name: Build and push frontend image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend-app:latest ./frontend
        docker push ${{ secrets.DOCKER_USERNAME }}/frontend-app:latest

    - name: Deploy Postgres
      run: kubectl apply -f ./k8s/postgres.yaml

    - name: Create DB credentials secret
      run: |
        kubectl delete secret db-credentials --ignore-not-found
        kubectl create secret generic db-credentials \
          --from-literal=POSTGRES_HOST=postgres-service \
          --from-literal=POSTGRES_USER=myuser \
          --from-literal=POSTGRES_PASSWORD=mypassword \
          --from-literal=POSTGRES_DB_NAME=employees_db \
          --from-literal=POSTGRES_PORT=5432

    - name: Deploy backend and frontend
      run: |
        kubectl apply -f ./k8s/backend-deployment.yaml
        kubectl apply -f ./k8s/frontend-deployment.yaml

    - name: Check all pods
      run: kubectl get pods --all-namespaces
